### ISSUE TITLE
训练到第10个epoch时，出现类型错误

### ISSUE THREAD

**Issue by lizhzh8** [lancopku/Global-Encoding#24]
错误如下：

**Comment by lizhzh8** [comment]
```
 [====================================================== 1000/1000 ====================>]  Step: 229ms | Tot: 3m52smss
epoch:   9, loss: 1014.513, time: 232.864, updates:    24000, accuracy: 78.39
evaluating after 24000 updates...
F_measure: [54.95, 49.41, 54.66] Recall: [53.03, 47.68, 52.76] Precision: [58.63, 52.85, 58.32]: 215ms | Tot: 0mss1ms
Decaying learning rate to 1.875e-05..................... 3/1000 ........................]  Step: 201ms | Tot: 421mss
 [====================================================== 1000/1000 ====================>]  Step: 215ms | Tot: 3m51smss
epoch:  10, loss: 739.646, time: 232.794, updates:    25000, accuracy: 84.69
evaluating after 25000 updates...
F_measure: [56.7, 51.45, 56.48] Recall: [54.78, 49.67, 54.56] Precision: [60.21, 54.77, 59.99]p: 190ms | Tot: 0ms8sms
 [====================================================== 1000/1000 ====================>]  Step: 231ms | Tot: 3m52smss
epoch:  10, loss: 741.760, time: 232.542, updates:    26000, accuracy: 84.26
evaluating after 26000 updates...
F_measure: [59.64, 54.74, 59.47] Recall: [57.87, 53.09, 57.7] Precision: [62.88, 57.82, 62.7]ep: 193ms | Tot: 0mss4ssss
Decaying learning rate to 9.375e-06===================== 670/1000 ......................]  Step: 202ms | Tot: 2m33smss
Traceback (most recent call last):
  File "train.py", line 322, in <module>
    main()
  File "train.py", line 316, in main
    print_log("Best %s score: %.2f\n" % (metric, max(params[metric])))
TypeError: must be real number, not tuple
```

**Comment by lizhzh8** [comment]
epoch=10，batch_size =4,eval_interval=1000,save_interval=300。其他没有变。
看train.py代码，我这是训练完成了，在算最好分数时，出现类型错误。不知道为什么？

**Comment by lizhzh8** [comment]
我现在把lcsts.yaml 中的评价方法由 rouge 改成 bleu后，没有报错。会给出一个结果。
```
epoch:   9, loss: 945.991, time: 226.441, updates:    24000, accuracy: 79.71
evaluating after 24000 updates...
BLEU = 47.76, 60.1/54.7/51.2/47.7 (BP=0.897, ratio=0.902, hyp_len=17883, ref_len=19825).]  Step: 168ms | Tot: 0ms      
Decaying learning rate to 1.875e-05....... 3/1000 ......................................]  Step: 200ms | Tot: 420ms    
 [======================================== 1000/1000 ==================================>]  Step: 217ms | Tot: 3m50s    
epoch:  10, loss: 677.400, time: 231.358, updates:    25000, accuracy: 85.92
evaluating after 25000 updates...
BLEU = 50.70, 63.0/57.9/54.4/51.1 (BP=0.898, ratio=0.903, hyp_len=17908, ref_len=19825).]  Step: 196ms | Tot: 0ms      
 [======================================== 1000/1000 ==================================>]  Step: 335ms | Tot: 3m50s    
epoch:  10, loss: 675.804, time: 230.997, updates:    26000, accuracy: 85.70
evaluating after 26000 updates...
BLEU = 54.03, 66.3/61.7/58.5/55.5 (BP=0.895, ratio=0.900, hyp_len=17845, ref_len=19825).]  Step: 202ms | Tot: 0ms      
 [========>.............................................................................]  Step: 1s355ms | Tot: 25s672mDecaying learning rate to 9.375e-06======= 670/1000 =======>............................]  Step: 199ms | Tot: 2m35s    
Best bleu score: 54.03
```

**Comment by lizhzh8** [comment]
难道和评价方法有关系吗？不知道为什么？

**Comment by jufengada** [comment]
您好，我想问一下，你的最好结果是多少呢？

**Comment by lizhzh8** [comment]
54.03
