### ISSUE TITLE
The validation error for testing score of rouge .

### ISSUE THREAD

**Issue by KelleyYin** [lancopku/Global-Encoding#9]
The model can be trained successful in first epoch. However, it will use validation set to test model performance , which  caused a bug.  the log is as followed.

 total number of parameters: 83289940 

 epoch:   1, loss: 51426.711, time: 2488.591, updates:    10000, accuracy: 27.78

218 Traceback (most recent call last):
219   File "train.py", line 332, in <module>
220     main()
221   File "train.py", line 324, in main
222     train_model(model, data, optim, i, params)
223   File "train.py", line 179, in train_model
224     score = eval_model(model, data, params)
225   File "train.py", line 252, in eval_model
226     score[metric] = getattr(utils, metric)(reference, candidate, params['log_path'], params['log'], config)
227   File "/data/mmyin/Global-Encoding/utils/metrics.py", line 58, in rouge
228     rouge_results = r.convert_and_evaluate()
229   File "/home/mmyin/anaconda3/lib/python3.6/site-packages/pyrouge-0.1.3-py3.6.egg/pyrouge/Rouge155.py", line 367,     in convert_and_evaluate
230     rouge_output = self.evaluate(system_id, rouge_args)
231   File "/home/mmyin/anaconda3/lib/python3.6/site-packages/pyrouge-0.1.3-py3.6.egg/pyrouge/Rouge155.py", line 342,     in evaluate
232     rouge_output = check_output(command, env=env).decode("UTF-8")
233   File "/home/mmyin/anaconda3/lib/python3.6/subprocess.py", line 336, in check_output
234     **kwargs).stdout
235   File "/home/mmyin/anaconda3/lib/python3.6/subprocess.py", line 418, in run
236     output=stdout, stderr=stderr)
237 subprocess.CalledProcessError: Command '['/data/mmyin/ROUGE/RELEASE-1.5.5/ROUGE-1.5.5.pl', '-e', '/data/mmyin/ROU    GE/RELEASE-1.5.5/data', '-c', '95', '-2', '-1', '-U', '-r', '1000', '-n', '4', '-w', '1.2', '-a', '-m', '/tmp/tmp    436z9iyl/rouge_conf.xml']' returned non-zero exit status 255.

**Comment by KelleyYin** [comment]
Does anybody know how to solve ?
